add basket ui
gomelviiv/-jewelry-shop pull request #6
Opened 2021-04-07 13:46 UTC by gomelviiv

2021-04-13 07:46 UTC, angelinabylitskaya requested changes

2021-04-13 07:46 UTC, angelinabylitskaya commented on index.html
> +</html>
<img width="216" alt="image" src="https://user-images.githubusercontent.com/19670773/114511553-bd239d80-9c40-11eb-95a6-158709ca6713.png">

2021-04-13 07:46 UTC, angelinabylitskaya commented on src/components/BasketItem/BasketItem.tsx
> +        <p>Категория: Подвеска, Бренд: Name Eman</p>
2 languages are used - bad.
Use English or add multi language text.
https://medium.com/@ricklee_10931/react-multi-lingual-with-react-i18next-57879f986168

2021-04-13 07:46 UTC, angelinabylitskaya commented on src/components/Header/HeaderMenu/HeaderMenu.tsx
> +              <img src="./assets/img/OJJo.png" alt="" />
Add alt text.

2021-04-13 07:46 UTC, angelinabylitskaya commented on src/styles/components/_banner.scss
> +}
No newline

2021-04-13 07:46 UTC, angelinabylitskaya commented on src/styles/components/_banner.scss
> +}
Add prettier to avoid code style issues.

2021-04-13 07:46 UTC, angelinabylitskaya commented on src/styles/components/_basket_item.scss
> +  .cart__item-img {
For more readability add empty line before each selector.

2021-04-13 07:46 UTC, angelinabylitskaya commented on src/styles/reset.scss
> +/* Указываем box sizing */
User comments only on English.

2021-04-13 07:46 UTC, angelinabylitskaya commented on src/styles/sections/_bottom_basket.scss
> +      color: #232323;
Move Colors to a variable file so they can be easily changed.

2021-04-13 07:46 UTC, angelinabylitskaya commented on src/styles/variables.scss
> +$secondary-color: #333333;
No newline

2021-04-13 07:46 UTC, angelinabylitskaya commented on src/styles/sections/_bottom_basket.scss
> +  .basket__bottom-details {
You can use parent ref here.
`&-details {`

2021-04-13 07:46 UTC, angelinabylitskaya commented on src/styles/sections/_bottom_basket.scss
> +  .basket__bottom-buttons {
`&-buttons {`

2021-04-13 07:46 UTC, angelinabylitskaya commented on src/styles/sections/_bottom_basket.scss
> +    .basket-back-btn {
Here also can be used the following code. Avoid too deep nesting.
```
.basket {

  &-back-btn {...}

  &-buy {...}
}
```

2021-04-14 19:21 UTC, gomelviiv commented
@angelinabylitskaya, I tried to fix all issues. In my next feature I correct all project by your template.

2021-04-20 08:53 UTC, merged