add redux for basket
gomelviiv/-jewelry-shop pull request #7
Opened 2021-04-08 10:49 UTC by gomelviiv

2021-04-13 07:55 UTC, angelinabylitskaya requested changes

2021-04-13 07:55 UTC, angelinabylitskaya commented on src/redux/reducers/basket/actionTypes.tsx
> +export const ADD_JEWELRY_TO_BASKET = 'ADD_JEWELRY_TO_BASKET';
Here an example of how to create typed actions:
```
const typesNames = [
  'LOGIN',
  'LOGIN_SUCCESS',
  'LOGIN_FAILURE',
  'LOGOUT',
  'CHECK_AUTH',
  'SET_AUTH',
  'GET_CURRENT_USER_SUCCESS',
  'GET_CURRENT_USER_FAILED',
  'DELETE_ERROR_MESSAGE',
] as const;

export type AuthActionType = {
  [Key in typeof typesNames[number]]: string;
};

export const prefix: string = 'AUTH';

export const authActionTypes: AuthActionType = createConstants<AuthActionType>(
  typesNames,
  prefix,
);

```
createConstants:
```
export const createConstants = <T>(
  constants: readonly any[],
  constantType: string,
): T =>
  constants.reduce((acc, constant: string) => {
    const prefix = constantType ? `${constantType}/` : '';
    acc[constant] = `${prefix}${constant}`;
    return acc;
  }, {});
```

All actions will be available inside authActionTypes object.

2021-04-13 07:55 UTC, angelinabylitskaya commented on src/redux/reducers/basket/index.tsx
> +const basketReducer = (state: IBasket = initialState, action: IBasketPayloadType<any>): IBasket => {
Move reducer to a separate file.

2021-04-13 07:55 UTC, angelinabylitskaya commented on src/redux/reducers/basket/index.tsx
> +const getTotalPriceNewItem = (arr: Array<IJewelryItem>) =>
Move helpers to a separate file.

2021-04-13 07:55 UTC, angelinabylitskaya commented on src/redux/reducers/basket/type.tsx
> +import { IJewelryItem } from '../jewelry/type';
Keep creating a file per entity.
Better to keep the following structure:
redux(or store or root-store)/
- features (a folder with all store features)/
--- basket (feature)/
----- index.ts (module export file)
----- reducers.ts
----- types.ts
----- actions.ts
----- selectors.ts
----- state.ts (initial state)
----- sagas.ts (if used)

2021-04-14 19:14 UTC, gomelviiv commented
@angelinabylitskaya, i tried to fix all issues.

2021-04-20 08:52 UTC, merged